-- mod-version:3
local syntax = require "core.syntax"

local digitsep = [[(?:\d[\d']*)]]
local fsuf = "[fFlL]?"
local isuf = [[(?:[lL][uU]|ll[uU]|LL[uU]|[uU][lL]\b|[uU]ll|[uU]LL|[uU]|[lL]\b|ll|LL)?]]

syntax.add {
  name = "Axe",
  files = { "%.axe$", "%.axec$" },
  comment = "//",
  block_comment = { "/*", "*/" },
  patterns = {
    { pattern = "//.*", type = "comment" },
    { pattern = { "/%*", "%*/" }, type = "comment" },
    { pattern = { '"', '"', '\\' }, type = "string" },
    { pattern = { "'", "'", '\\' }, type = "string" },
    { pattern = { "`", "`", '\\' }, type = "string" },
    { regex = digitsep.."%.?"..digitsep.."?(?:[eE][-+]?"..digitsep..")?"..fsuf, type = "number" },
    { regex = "0x[0-9a-fA-F][0-9a-fA-F']*"..isuf, type = "number" },
    { regex = "0()[0-7][0-7']*"..isuf, type = { "keyword", "number" } },
    { regex = digitsep..isuf, type = "number" },
    { pattern = "\\b(if|when|is|elif|else|for|in|switch|case|default|parallel|single|loop|break|continue|return|while|test|assert|use|platform|and|or|to|mod|enum|union|unsafe|opaque|extern|foreign)\\b", type = "keyword" },
    { pattern = "\\b(pub|def|val|mut|model|macro|raw|overload|list|put)\\b", type = "keyword2" },
    { pattern = "\\b(ref|ref_of|addr_of|cast)\\b", type = "keyword" },
    { pattern = "\\b(u8|i8|u16|i16|u32|i32|u64|i64|f32|f64|bool|char|void|usize|generic|untyped)\\b", type = "keyword2" },
    { pattern = "\\bchar%*\\b", type = "keyword2" },
    { pattern = "\\b[A-Z][a-zA-Z0-9_]*\\b", type = "keyword2" },
    { pattern = "\\b(def|macro)\\s+([a-zA-Z_][a-zA-Z0-9_]*)", type = {"keyword2", "function"} },
    { pattern = "\\b([a-z_][a-zA-Z0-9_]*)%s*%(", type = "function" },
    { pattern = "[%+%-=/%*%%]", type = "operator" },
    { pattern = "==|!=|<=|>=|<|>", type = "operator" },
    { pattern = "\\b(and|or)\\b", type = "operator" },
    { pattern = "=", type = "operator" },
    { pattern = "\\b(true|false)\\b", type = "literal" },
    { pattern = "\\bnil\\b", type = "literal" },
    { pattern = "\\b[A-Z_][A-Z0-9_]*\\b", type = "literal" },
    { pattern = "\\braw%s*%{.-%}", type = "keyword2" },
  },
  symbols = {
    ["if"] = "keyword",
    ["else"] = "keyword",
    ["elif"] = "keyword",
    ["for"] = "keyword",
    ["while"] = "keyword",
    ["return"] = "keyword",
    ["break"] = "keyword",
    ["continue"] = "keyword",
    ["true"] = "literal",
    ["false"] = "literal",
    ["nil"] = "literal",
    ["def"] = "keyword2",
    ["macro"] = "keyword2",
    ["pub"] = "keyword2",
    ["val"] = "keyword2",
    ["mut"] = "keyword2",
    ["model"] = "keyword2",
    ["raw"] = "keyword2",
    ["u8"] = "keyword2",
    ["i8"] = "keyword2",
    ["u16"] = "keyword2",
    ["i16"] = "keyword2",
    ["u32"] = "keyword2",
    ["i32"] = "keyword2",
    ["u64"] = "keyword2",
    ["i64"] = "keyword2",
    ["f32"] = "keyword2",
    ["f64"] = "keyword2",
    ["bool"] = "keyword2",
    ["char"] = "keyword2",
    ["void"] = "keyword2",
    ["usize"] = "keyword2",
    ["generic"] = "keyword2",
    ["untyped"] = "keyword2",
  },
}
